# Generated by Django 4.0.6 on 2023-06-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_attendence_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='Logout',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
