# Generated by Django 4.0.6 on 2023-06-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_attendence_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='Logout',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
